[DeathDragon]
	#Minimal aura.
	minAura = 5000000.0
	#Maximum aura.
	maxAura = 5000000.0
	#Minimal magicule.
	minMagicule = 1.0E7
	#Maximum magicule.
	maxMagicule = 1.0E7
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 1240.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 8500.0
	#Bonus Attack Damage.
	attack = 6.0
	#Bonus Attack Speed.
	attackSpeed = 0.699999988079071
	#Bonus Knockback Resistance.
	knockbackResistance = 1.0
	#Bonus Movement Speed.
	movementSpeed = 0.1
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.699999988079071
	#List of possible pre evolutions.
	preEvolutions = ["tensura:divine_skeleton"]
