[DragonWolf]
	#Minimal aura.
	minAura = 5000000.0
	#Maximum aura.
	maxAura = 5000000.0
	#Minimal magicule.
	minMagicule = 1.0E7
	#Maximum magicule.
	maxMagicule = 1.0E7
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 1330.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 9625.0
	#Bonus Attack Damage.
	attack = 7.0
	#Bonus Attack Speed.
	attackSpeed = 0.20000000298023224
	#Bonus Knockback Resistance.
	knockbackResistance = 1.0
	#Bonus Movement Speed.
	movementSpeed = 0.07000000029802322
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.824999988079071
	#Bonus Step Height.
	stepHeight = 0.5
	#List of possible pre evolutions.
	preEvolutions = ["tensura:divine_wolf"]
