[DragonBoar]
	#Minimal aura.
	minAura = 1.0E7
	#Maximum aura.
	maxAura = 1.0E7
	#Minimal magicule.
	minMagicule = 5000000.0
	#Maximum magicule.
	maxMagicule = 5000000.0
	#Bonus Size.
	size = 0.5
	#Bonus Max Health.
	maxHealth = 1180.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 8440.0
	#Bonus Attack Damage.
	attack = 5.0
	#Bonus Attack Speed.
	attackSpeed = 0.699999988079071
	#Bonus Knockback Resistance.
	knockbackResistance = 1.0
	#Bonus Movement Speed.
	movementSpeed = 0.09
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.8
	#List of possible pre evolutions.
	preEvolutions = ["tensura:divine_boar"]
