[FallenDragon]
	#Minimal aura.
	minAura = 5000000.0
	#Maximum aura.
	maxAura = 5000000.0
	#Minimal magicule.
	minMagicule = 1.02E7
	#Maximum magicule.
	maxMagicule = 1.03E7
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 1280.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 8350.0
	#Bonus Attack Damage.
	attack = 6.5
	#Bonus Attack Speed.
	attackSpeed = 0.8
	#Bonus Knockback Resistance.
	knockbackResistance = 1.0
	#Bonus Movement Speed.
	movementSpeed = 0.09
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.8
	#List of possible pre evolutions.
	preEvolutions = ["mysticism:fallen", "trorigins:fallen_of_origin"]
