[MysticDragon]
	#Minimal aura.
	minAura = 7700000.0
	#Maximum aura.
	maxAura = 7750000.0
	#Minimal magicule.
	minMagicule = 7700000.0
	#Maximum magicule.
	maxMagicule = 7750000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 1260.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 8350.0
	#Bonus Attack Damage.
	attack = 6.0
	#Bonus Attack Speed.
	attackSpeed = 0.8
	#Bonus Knockback Resistance.
	knockbackResistance = 1.0
	#Bonus Movement Speed.
	movementSpeed = 0.09
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.8
	#List of possible pre evolutions.
	preEvolutions = ["mysticism:mystic_angel", "trorigins:mystic_angel_of_origin"]
