[SpecialVariant]
	#One of how many chances for an otherworlder to spawn as Shizu.
	shizuChance = 30
	#One of how many chances for an otherworlder to spawn as Hinata Sakaguchi.
	hinataChance = 50
	#One of how many chances for a hell caterpillar to spawn as a gehenna caterpillar.
	gehennaCaterpillarChance = 20
	#One of how many chances for a hell caterpillar cocoon to mutate to a gehenna moth.
	gehennaCocoonChance = 60
	#One of how many chances for a hell moth to spawn as or evolve to a gehenna moth.
	gehennaMothChance = 20
	#One of how many chances for a hound dog to have a snake tail.
	houndDogSnakeChance = 20
	#One of how many chances for an orc to be an orc lord.
	orcLordChance = 900
	#One of how many chances for an orc to be a royal orc.
	orcRoyalChance = 100
	#One of how many chances for a Royal Orc to have Self-Regeneration.
	orcRoyalLordChance = 7
	#One of how many chances for a Direwolf to be an Alpha.
	alphaWolf = 10
	#One of how many chances for a Tempest Wolf to have the Star birthmark.
	starBirthmark = 16
	#The percentage chance for a direwolf pack to be evolved
	evolvedPack = 40
	#The percentage chance for a direwolf pack to be Elemental Fang based on biomes
	elementalFangPack = 65
	#The percentage chance for a direwolf pack to be Tempest Wolves
	tempestWolfPack = 10
	#One of how many chances for a slime to spawn as Metal Slime.
	metalSlimeChance = 500
	#One of how many chances for a slime to spawn as Supermassive Slime.
	supermassiveSlimeChance = 1000
	#One of how many chances for a medium spirit spawned in Ancient Forest to spawn as a greater spirit.
	greaterSpiritChance = 400

#Spawn probability for mobs (1 in X chance). First value is Day, Second is Night.
#Examples: 1=100%, 5=20%, 10=10%. 0=disabled.
[SpawnChance]
	otherworlder = [60, 40]
	aquaFrog = [32, 16]
	archDaemon = [160, 80]
	armorsaurus = [10, 6]
	armyWasp = [24, 16]
	barghest = [16, 12]
	basilisk = [22, 16]
	beastGnome = [32, 16]
	blackSpider = [18, 12]
	bladeTiger = [18, 14]
	cattledeer = [14, 10]
	direwolf = [6, 5]
	dragonPeacock = [18, 14]
	evilCentipede = [24, 16]
	featheredSerpent = [32, 16]
	giantAnt = [18, 14]
	giantBat = [0, 10]
	giantBear = [24, 16]
	giantCod = [14, 18]
	giantSalmon = [14, 18]
	greaterDaemon = [120, 60]
	hellCaterpillar = [18, 14]
	hellMoth = [26, 20]
	hornedBear = [24, 16]
	hornedRabbit = [16, 12]
	houndDog = [30, 16]
	hoverLizard = [16, 12]
	knightSpider = [18, 14]
	landfish = [16, 12]
	leechLizard = [18, 14]
	lesserDaemon = [80, 40]
	megalodon = [60, 30]
	oneEyedOwl = [22, 16]
	orc = [10, 8]
	pegasus = [48, 24]
	phantaspore = [22, 16]
	salamander = [32, 16]
	sissie = [22, 22]
	slime = [8, 6]
	spearToro = [14, 14]
	unicorn = [48, 24]
	tempestSerpent = [26, 20]
	wingedCat = [32, 16]
