name = "Tensura: Sovereign Rebirth"
author = "TSR Team"
version = "1.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0da89e420dd9a6c59eebe6ca83a6730c8037bcced9de84120a5ed32287c90962"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
