name = "Tensura: Sovereign Rebirth"
author = "TSR Team"
version = "1.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dcc8f26106907177ec42f615ec90943762a9110f8bc251129cbc9a0a7936a7f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
